#pragma once

#include "syscall.h"
#include "printers.h"

#define SYSCALL_MAX64	547

const t_syscall	SYSCALL_TABLE64[SYSCALL_MAX64 + 1] = {
	[0]		= {"read", &printer_read},
	[1]		= {"write", &printer_write},
	[2]		= {"open", &printer_open},
	[3]		= {"close", &printer_close},
	[4]		= {"stat", &printer_stat},
	[5]		= {"fstat", &printer_fstat},
	[6]		= {"lstat", &printer_lstat},
	[7]		= {"poll", &printer_poll},
	[8]		= {"lseek", &printer_lseek},
	[9]		= {"mmap", &printer_mmap},
	[10]	= {"mprotect", &printer_mprotect},
	[11]	= {"munmap", &printer_munmap},
	[12]	= {"brk", &printer_brk},
	[13]	= {"rt_sigaction", &printer_rt_sigaction},
	[14]	= {"rt_sigprocmask", &printer_rt_sigprocmask},
	[15]	= {"rt_sigreturn", &printer_rt_sigreturn},
	[16]	= {"ioctl", &printer_ioctl},
	[17]	= {"pread64", &printer_pread64},
	[18]	= {"pwrite64", &printer_pwrite64},
	[19]	= {"readv", &printer_readv},
	[20]	= {"writev", &printer_writev},
	[21]	= {"access", &printer_access},
	[22]	= {"pipe", &printer_pipe},
	[23]	= {"select", &printer_select},
	[24]	= {"sched_yield", &printer_sched_yield},
	[25]	= {"mremap", &printer_mremap},
	[26]	= {"msync", &printer_msync},
	[27]	= {"mincore", &printer_mincore},
	[28]	= {"madvise", &printer_madvise},
	[29]	= {"shmget", &printer_shmget},
	[30]	= {"shmat", &printer_shmat},
	[31]	= {"shmctl", &printer_shmctl},
	[32]	= {"dup", &printer_dup},
	[33]	= {"dup2", &printer_dup2},
	[34]	= {"pause", &printer_pause},
	[35]	= {"nanosleep", &printer_nanosleep},
	[36]	= {"getitimer", &printer_getitimer},
	[37]	= {"alarm", &printer_alarm},
	[38]	= {"setitimer", &printer_setitimer},
	[39]	= {"getpid", &printer_getpid},
	[40]	= {"sendfile", &printer_sendfile},
	[41]	= {"socket", &printer_socket},
	[42]	= {"connect", &printer_connect},
	[43]	= {"accept", &printer_accept},
	[44]	= {"sendto", &printer_sendto},
	[45]	= {"recvfrom", &printer_recvfrom},
	[46]	= {"sendmsg", &printer_sendmsg},
	[47]	= {"recvmsg", &printer_recvmsg},
	[48]	= {"shutdown", &printer_shutdown},
	[49]	= {"bind", &printer_bind},
	[50]	= {"listen", &printer_listen},
	[51]	= {"getsockname", &printer_getsockname},
	[52]	= {"getpeername", &printer_getpeername},
	[53]	= {"socketpair", &printer_socketpair},
	[54]	= {"getsockopt", &printer_getsockopt},
	[55]	= {"setsockopt", &printer_setsockopt},
	[56]	= {"clone", &printer_clone},
	[57]	= {"fork", &printer_fork},
	[58]	= {"vfork", &printer_vfork},
	[59]	= {"execve", &printer_execve},
	[231]	= {"exit_group", &printer_exit_group},
};